[labels]
app_name = Feeds

notification_topic_post = New posts
notification_topic_mention = Mentions
notification_topic_comment_thread = Replies in threads I follow
notification_topic_comment_mine = Replies to my comments
notification_topic_reaction_thread = Reactions in threads I follow
notification_topic_reaction_mine = Reactions to my comments
