/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFeedIdRouteImport } from './routes/_authenticated/$feedId'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedFeedIdPostIdRouteImport } from './routes/_authenticated/$feedId_.$postId'
import { Route as AuthenticatedFeedIdSettingsRouteImport } from './routes/_authenticated/$feedId_.settings'
import { Route as AuthenticatedFeedIdSourcesRouteImport } from './routes/_authenticated/$feedId_.sources'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedIdRoute = AuthenticatedFeedIdRouteImport.update({
  id: '/$feedId',
  path: '/$feedId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedIdPostIdRoute =
  AuthenticatedFeedIdPostIdRouteImport.update({
    id: '/$feedId_/$postId',
    path: '/$feedId/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedIdSettingsRoute =
  AuthenticatedFeedIdSettingsRouteImport.update({
    id: '/$feedId_/settings',
    path: '/$feedId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedIdSourcesRoute =
  AuthenticatedFeedIdSourcesRouteImport.update({
    id: '/$feedId_/sources',
    path: '/$feedId/sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$feedId': typeof AuthenticatedFeedIdRoute
  '/find': typeof AuthenticatedFindRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/$feedId/$postId': typeof AuthenticatedFeedIdPostIdRoute
  '/$feedId/settings': typeof AuthenticatedFeedIdSettingsRoute
  '/$feedId/sources': typeof AuthenticatedFeedIdSourcesRoute
}
export interface FileRoutesByTo {
  '/$feedId': typeof AuthenticatedFeedIdRoute
  '/find': typeof AuthenticatedFindRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/': typeof AuthenticatedIndexRoute
  '/$feedId/$postId': typeof AuthenticatedFeedIdPostIdRoute
  '/$feedId/settings': typeof AuthenticatedFeedIdSettingsRoute
  '/$feedId/sources': typeof AuthenticatedFeedIdSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$feedId': typeof AuthenticatedFeedIdRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$feedId_/$postId': typeof AuthenticatedFeedIdPostIdRoute
  '/_authenticated/$feedId_/settings': typeof AuthenticatedFeedIdSettingsRoute
  '/_authenticated/$feedId_/sources': typeof AuthenticatedFeedIdSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$feedId'
    | '/find'
    | '/saved'
    | '/$feedId/$postId'
    | '/$feedId/settings'
    | '/$feedId/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$feedId'
    | '/find'
    | '/saved'
    | '/'
    | '/$feedId/$postId'
    | '/$feedId/settings'
    | '/$feedId/sources'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$feedId'
    | '/_authenticated/find'
    | '/_authenticated/saved'
    | '/_authenticated/'
    | '/_authenticated/$feedId_/$postId'
    | '/_authenticated/$feedId_/settings'
    | '/_authenticated/$feedId_/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$feedId': {
      id: '/_authenticated/$feedId'
      path: '/$feedId'
      fullPath: '/$feedId'
      preLoaderRoute: typeof AuthenticatedFeedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$feedId_/$postId': {
      id: '/_authenticated/$feedId_/$postId'
      path: '/$feedId/$postId'
      fullPath: '/$feedId/$postId'
      preLoaderRoute: typeof AuthenticatedFeedIdPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$feedId_/settings': {
      id: '/_authenticated/$feedId_/settings'
      path: '/$feedId/settings'
      fullPath: '/$feedId/settings'
      preLoaderRoute: typeof AuthenticatedFeedIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$feedId_/sources': {
      id: '/_authenticated/$feedId_/sources'
      path: '/$feedId/sources'
      fullPath: '/$feedId/sources'
      preLoaderRoute: typeof AuthenticatedFeedIdSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedIdRoute: typeof AuthenticatedFeedIdRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFeedIdPostIdRoute: typeof AuthenticatedFeedIdPostIdRoute
  AuthenticatedFeedIdSettingsRoute: typeof AuthenticatedFeedIdSettingsRoute
  AuthenticatedFeedIdSourcesRoute: typeof AuthenticatedFeedIdSourcesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedIdRoute: AuthenticatedFeedIdRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFeedIdPostIdRoute: AuthenticatedFeedIdPostIdRoute,
  AuthenticatedFeedIdSettingsRoute: AuthenticatedFeedIdSettingsRoute,
  AuthenticatedFeedIdSourcesRoute: AuthenticatedFeedIdSourcesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
